### PR TITLE
Add password reset feature with emails

### PR DESCRIPTION
**Pull request by matteverson**
This completes the password reset system. Tokens are
generated by mongoose-token using the node crypto library. The token is
stored in the DB and valid for 1 hour. An email containing the token is
sent to them using Mailgun. The free tier provides 300-400 free emails
per day.

The client portion of the feature is a page that is accessible
without authentication containing a form for the token, the user email,
and the new password. This form posts to the reset_token endpoint from
this commit.

### CODE REVIEW

**Comment by awesomeaniruddh** [comment]
Not sure what I'm missing, but running `npm install` on this is giving me `unmet dependency` errors?

**Comment by matteverson** [comment]
Yes, are you trying this on C9? What's the full output of npm install?

**Comment by awesomeaniruddh** [comment]
Yes, unfortunately I'm having to resort to C9. I am just getting a bunch of `unmet dependency` errors.
image

**Comment by awesomeaniruddh** [comment]
Its C9 killing the process because of the memory limit. *phew*.

I was using a DO server with a swapfile, which allowed me to not hit the limit but I have no idea how to actually start the app there.

**Comment by matteverson** [comment]
To use password reset emails in your dev environment, set MAILGUN_API_KEY and MAILGUN_DOMAIN in server/config/local.env.js

**Pull request merged**
